version: '3.9'
services:
  api:
    build: ./src/AppHost
    ports:
      - '5000:80'
    depends_on:
      - postgres
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=postgres;Database=coinplay_db;Username=coinplay;Password=coinplay123
      - ConnectionStrings__Redis=redis:6379

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: coinplay_db
      POSTGRES_USER: coinplay
      POSTGRES_PASSWORD: coinplay123
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
